#ENC[AES256_GCM,data:KhcNTel4ErkFycXGsTfvx1sJpEWom6evkLTvdA0aaHv1isdKY1zU8voFRA5vu8XKg3EPTRrz5tvqIgU/L5D1xSSn,iv:UpFwDOOBPcjOa2vKKSsjqxvO4N/o4CCrb1DfA1ixvV4=,tag:dkPzf3I42n7GIbWuGB4QBg==,type:comment]
okta_discovery_url: ENC[AES256_GCM,data:UtX2tqFsgJiAHvW5wgzUNKZQphb1AFgUlFjFtbEEDByPwNM=,iv:wYVbQbuMezJg7dt1JvvYDClPUhfs09ObiJKC2iqpiN8=,tag:QlKU6F2vL6UB3lQZ+aDlDg==,type:str]
okta_client_id: ENC[AES256_GCM,data:moPlcUTTxFTWU8Tc5ZA0AUOcV+E=,iv:7nwLuSqlCIfCp6Z3cBWW0ms/zxZtZyJJSIS5xIjbYQk=,tag:mfUc0QfMpM33lVL1SaLciw==,type:str]
okta_client_secret: ENC[AES256_GCM,data:00JV2PhMj+DhEvQDzMTuuSFgsRWdIfQ+xFrjUIPEFg5bgqWYS3kiDsmQix8way/evWO7rlQfWHA66GQZqT55GQ==,iv:A+SmejNVnrNyUzCYxL38kRzBa51TpRa5B9mCUm4Sd8g=,tag:SPP01ScDeL7JJpsJcEMbeQ==,type:str]
#ENC[AES256_GCM,data:OLiVogoII2JrAVTvOm3l/blJd+nxxO6GHtuUiGl7sZ1I560hkuzgFClTmpybxws22s+sBy8PhJmYMhfUmgCR46Zw,iv:IDgMI/ZKQMdhxM27h+PovM2O0WsFhvgdmHYsaCjl8j4=,tag:Z71wFgBED3q6g/fjQ4uu8Q==,type:comment]
#ENC[AES256_GCM,data:2SzbLgjOq6i6bjXce+XYoKnL9/EN3otT60iii73p,iv:MAiAX935CbcYA/tmOezPJDIHyCi/S34KmkciIYCj4bE=,tag:ZYMt+rOQOnglriOC+8Uvqw==,type:comment]
sops:
    age:
        - recipient: age18p59q2xtlsg8zsu9xk60wg852eqqah5ppp2pxkfn0kyadl6exfkq2272r8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUHpLVmduUnRIMmFlU0tl
            eHcxSWpUdm9XRHhFdG15QmxMRTVSTnppblVzCjZXSkpVNE54K2JnVkxJT1VvL29V
            WjdOWmE3RGpYV1lCRVlEak5IbHhpckUKLS0tIGRNQVNiVWs4d202UFlhaW1YampD
            M3NwcnhUK05Rb3pBaWZ0ZlhudVVwMEkKd5xqQ1pJTT0L4aAVro/M6/saTYY04/1H
            8jNSZMK4QO+AJlMAdRMJ6ou9M6CSj6u02AZlOPE3DPx4rao3Ktwkhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-01T02:05:02Z"
    mac: ENC[AES256_GCM,data:6AY4sh5Lfgd/cWPV0Z6xddW1zaapGRSIi7DJbd6YyVu4ehpBpEgs0cCp4xqxouiqAU3ldSoNhozoC2c1FtLMXAoqB6U3ALKYMOIcLiPhmSpo/y3g0cBd5dnExFF2Kygg5wWBUNBDwLzdx0OE2adlu7wFFUuF+Yiy21QQrCca8Mw=,iv:S60SC9k3yr/nhDlrex6X5XXPPaVftzhAajXl7G88/T4=,tag:4t67dlIC2w/9WRHJXCIbDw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
