#ENC[AES256_GCM,data:KjfN/40H8jDrzljN46x8vg+AYyy92gXI28MdagUBwDjucuo5fhKq8uGv5Rcgl9cWl5u/pxniN9tf2BhkAELsDEgf,iv:Fx7qYSRSf1glHoaWpY8XzfCFxG5KEGs9D/3kIUZywdw=,tag:8wxGJB9DpqAtyYTr2hmkiA==,type:comment]
okta_discovery_url: ENC[AES256_GCM,data:CoyjuBVgYSqX6uRJt4LiIJc5mWSvO9X+vupaLqc/qk7t5DQ=,iv:QUbF1MyvLRtnK+Y1gwPKCnVusHBJ0wAc9k6CRi0Gjq4=,tag:I573apbyxqwYzZDxjtW9Nw==,type:str]
okta_client_id: ENC[AES256_GCM,data:mIMmHq2H1tkQK8Wn7tK4Rv7t6rA=,iv:IksNUzPNVL8vcsZZNV6GdNOFN9ajHkThYHCoGG21QAk=,tag:GncJ+qYRHbHjjgGJ2E8pqw==,type:str]
okta_client_secret: ENC[AES256_GCM,data:p6KLbtr4Tzt9eNe4slYQCXkt2x7fmtIvynwALgMVsZn46XcMe0Mjzvn6q87hBrhR374BrDqnsnSTC+MRloQJ2w==,iv:pycYpLYXmvjkgUYbnC7DA+YttwFZ05XGwjcvkCVtruo=,tag:qWtjihp5Nvkf9YZyoxNZXA==,type:str]
#ENC[AES256_GCM,data:acMTtfMMJ8zrM0OiEQf2ZeWG1ln2UBUaKMZ5YC0JrS6tz/KiMsMKDJAm1hfS9/D9M+W74OSEcGyw9B25IVkM22+C,iv:yN95zqOA+K0ggveERazgOrlVc++BskE9zT9jrY9Evx0=,tag:oXdLB0CCFMNb1lJOLImPzA==,type:comment]
#ENC[AES256_GCM,data:WJDkUGimX+ABpZA7pqckIr969OUB8PYxBXLY7rM5,iv:ecPgdahETISCWcUoYWZt48r37ir28BQoNSQ/73G64iU=,tag:k7a0ZDFRsnFqPuZTrIDmBA==,type:comment]
sops:
    age:
        - recipient: age18p59q2xtlsg8zsu9xk60wg852eqqah5ppp2pxkfn0kyadl6exfkq2272r8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdUpiYnlKWldSWWxOTTlZ
            UEZhZGJHZjRTbjR3MkRFYmZQbktsczlVNWhVClE2djlFWWRpVmYyN0tBRHNERncv
            VDU5SDhOczhPRzE5eUw2Zmh0eDhQQ1kKLS0tIG5xMUZPNzVDUE0wenp6bmtacXNX
            Q2Mwd0VER2s1QXdWQ0g1alAyT0pSYUEKpvrff3lUD7EIyTom5WLJMZfy22ZW2UbR
            UMQ703OGf22zFXDg2PpEdKprhIKSfVTgE0Ma3n6I2L5lRbtfU8NHyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-01T01:56:57Z"
    mac: ENC[AES256_GCM,data:aYhGLhmC4j3YwEK5lAnDNP15kwVdzbnqYlT1xZ2lVPM5ZHvVBQhxOrrjbNxY6vMl29scTVAxsO2T+sXxa2LNgme234qeoew883apDW7RK7BpVsGEzXcTWQbrTIMcGfRpt+rImNZ47e8benjFYPX746B6P2kOu64FUvZHxCxZA4s=,iv:KWRXFn+c2w83nyHjx0hRhAqhF5Yxcn3+MVe4QSbw93w=,tag:9BNse5c6IbBp+cXaoi2J2A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
