#ENC[AES256_GCM,data:20mRlA7BI3l6PgCabtpUoUNtMrmuZHBaLnAVrFOsLGv3LdXpH5vpAyKHJWpQ1FoN0dXIDR2t6TZQV/Sgtq46Qq55,iv:hnxULDKAD6JtmXEsvXFn9xCx/GM0Woi69woP2kgLzak=,tag:vu3hkbnKFJoEwAtm8lz5tw==,type:comment]
okta_discovery_url: ENC[AES256_GCM,data:rjy+FVTP5t/1zlHh4OwkjPBO5phAdXfE4aNjS79OYg7hSPM=,iv:EbI6U/DEt3npXkWp06+Qjv7nbBcXvxx74mauQaciwFw=,tag:hFpyGHoHBjfTmzVFAYMKlA==,type:str]
okta_client_id: ENC[AES256_GCM,data:kTBo5YssjvFispdHsg5j/VPFTGw=,iv:LR91aBL1Mn1AdTXlhJ/t7w/ceLWfXlap8nM/zIz59E8=,tag:a6/Vy4J+U1ujYDrDSemlXw==,type:str]
okta_client_secret: ENC[AES256_GCM,data:eNq5/N1HQdfBdfpDWPSBBvIKkr5nzyNn63VHvokwv4HhfP1jPi0H4Y3Fz5/MlxIP88uXkmORy56kHwsYK3jMiA==,iv:AnylxRSLp4VuytgefRbgbeG+WOebDVRUXyOwXIGUkyA=,tag:JXnOeu0eVkKpPlnvE+REhw==,type:str]
#ENC[AES256_GCM,data:E6MyiZS9uMqZ7I3HA+QjQLfENBAnQHRt3PnxjLHf6JJCvEv95tT2sQo05Waha+0trYHbYzxfDrYsi5SQwUH3R0jr,iv:WXX42TwOhSFVSZej8zHBBSWhMMBvhMG0uP8FLnr5sS0=,tag:CTwxCzC+cbQ3WD71ssaqfQ==,type:comment]
#ENC[AES256_GCM,data:CzTODutZdjtyeNOFfdna+mnV3UtfGaoC9fJLAqA+,iv:ZB+X0H1mVyJM3eM+s4LMabMY+e3sxbGqL7LGzzNDwuo=,tag:SMnLK6z+FRjWG0iZ3ulQPg==,type:comment]
sops:
    age:
        - recipient: age18p59q2xtlsg8zsu9xk60wg852eqqah5ppp2pxkfn0kyadl6exfkq2272r8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMWJXUy9MeDR2Vld4Vmgy
            QTVBdklwenUvOGhOL3p3MFVVMzRDQVBKRkVZCjBmTHVXY2VhaFRvTTd0NzVRZUht
            NytlU25wWVdaUEh3S3B5ZVlKbmlmOTQKLS0tIFFNb2IramlDWTY2VFVScFlPWUMr
            RTZKbW8vYmRxRFdacGF5NThwd2dtdzAK1AiD1HYpKpYIa4mmlh7pAHRxq3IV9Km/
            PWSnTwMeq+Y7cPSqKwQ96e7sFBUkTmqf9eL3FP5kc5ru9xpunCifMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-31T01:55:32Z"
    mac: ENC[AES256_GCM,data:BTClkBYcX/SZrtf8X9u9eWTmEs2kYreMW6MfLL/amlACh8KKL8+qbgzFCibZxRSnL9rj3LD85Fl8BCZRVjK3tDvHdAS6tAMvCupLtXAyN38vJDxxzFACrpwuAkF1HMcZHeAmeQE55o3f4diqOHicuhnx1LzLkSSMCNgOcSdqVO0=,iv:esYiAnqcAU4gVai1TrHtlSHUIWrRXLrR1E2eIX1FhGE=,tag:TR6TQbNWWXTef85375nOqA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
